import './jsx/jsx-basic-1'
import './jsx/jsx-basic-2'
import './jsx/jsx-with-style'
import './jsx/test.js'
import './component-basic/first-component'
import './component-basic/animal-container.js'
import './component-basic/props-basic-1.js' 