// import './jsx/jsx-basic-1'
// import './jsx/jsx-basic-2'
// import './jsx/jsx-with-style'
// import './jsx/test.js'
// import './component-basic/first-component'
// import './component-basic/animal-container.js'
// import './component-basic/props-basic-1.js'

// import './component-basic/props-children.js'
// import './component-basic/default-props.js'
// import './component-intermediate/state-study-1.js'
// import './component-intermediate/state-study-2.js'
// import './component-intermediate/state-study-3.js'
// import './test/test1.js'
// import './test/test2.js'
// import './component-intermediate/state-study-with-inner-object.js'
// import './component-intermediate/counter-with-hook-caveat.js'
import './component-intermediate/manipulate-list.js'